apiVersion: v1
kind: Service
metadata:
    name: "checkmkaks-20ee"
    labels:
        app: "checkmkaks-20ee"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "checkmkaks-20ee"