on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: iitmonitoringregistry.azurecr.io
        username: ${{ secrets.acr_iitmonitoringregistry_username }}
        password: ${{ secrets.acr_iitmonitoringregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/fortune_cookies" -f  "fortune_cookies/Dockerfile" -t iitmonitoringregistry.azurecr.io/checkmkaks:${{ github.sha }}
        docker push iitmonitoringregistry.azurecr.io/checkmkaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_checkmkaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep checkmk-aksbeff | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace checkmk-aksbeff`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: checkmk-aksbeff
        container-registry-url: iitmonitoringregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_iitmonitoringregistry_username }}
        container-registry-password: ${{ secrets.acr_iitmonitoringregistry_password }}
        secret-name: checkmkaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: checkmk-aksbeff
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          iitmonitoringregistry.azurecr.io/checkmkaks:${{ github.sha }}
        imagepullsecrets: |
          checkmkaksdockerauth